version: "3.9"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/volume:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: default
      POSTGRES_PASSWORD: 9yEumx4mEb
      POSTGRES_DB: default

  redis:
    image: redis
    command: redis-server --requirepass 9QYVMZNxuSmPp1GyvNs38FKh4rqBMZfCMrCWkXlnmpSm
    ports:
      - "6379:6379"
    volumes:
      - ./redis/volume:/data
